import './globals.css'
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {StoreProvider} from "@/redux/StoreProvider";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }): React.ReactElement {
    return (
        <html lang="en">
            <body>
                <div className='wrapper'>
                    <StoreProvider>
                        <Header />
                        <div className='container'>
                            {children}
                        </div>
                        <Footer />
                    </StoreProvider>
                </div>
            </body>
        </html>
    )
}
